//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ALERT_MSG
    {
        public int ALERT_ID { get; set; }
        public Nullable<int> ALERT_KIND { get; set; }
        public string ALERT_TITLE { get; set; }
        public string ALERT_MSG { get; set; }
        public Nullable<System.DateTime> ALERT_TIM { get; set; }
        public string ALERT_IP { get; set; }
        public Nullable<int> ALERT_STS { get; set; }
    }
}
