//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GAME_TEAM
    {
        public int TEAM_ID { get; set; }
        public string TEAM_NAME { get; set; }
        public string TEAM_ENNAME { get; set; }
        public string TEAM_COUNTRY { get; set; }
        public string TEAM_LOGO { get; set; }
    }
}
