//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GAME
    {
        public int GAME_ID { get; set; }
        public Nullable<int> GAME_KIND { get; set; }
        public string GAME_GRP { get; set; }
        public Nullable<int> GAME_GRP_ID { get; set; }
        public Nullable<int> GAME_LEAGUE { get; set; }
        public Nullable<int> M_TEAM { get; set; }
        public string M_TEAM_NAME { get; set; }
        public Nullable<int> C_TEAM { get; set; }
        public string C_TEAM_NAME { get; set; }
        public Nullable<System.DateTime> GAME_BEGIN { get; set; }
        public Nullable<int> GAME_STS { get; set; }
    }
}
