//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LEAGUE
    {
        public int LEAGUE_ID { get; set; }
        public string LEAGUE_NAME { get; set; }
        public Nullable<int> LEAGUE_KIND { get; set; }
        public string LEAGUE_LOGO { get; set; }
        public string LEAGUE_ENNAME { get; set; }
        public string LEAGUE_ORG { get; set; }
    }
}
