//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MESSAGE_BOX
    {
        public int MSG_ID { get; set; }
        public string USER_ID { get; set; }
        public string SEND_USER { get; set; }
        public string MSG_TITLE { get; set; }
        public string MSG_CONTEXT { get; set; }
        public Nullable<System.DateTime> MSG_TIME { get; set; }
        public Nullable<int> MSG_STS { get; set; }
    }
}
