//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER_GROUP
    {
        public int USER_GROUP_ID { get; set; }
        public Nullable<int> USER_GROUP { get; set; }
        public Nullable<int> GROUP_ACC_MAX { get; set; }
        public Nullable<double> GROUP_RET_RETIO { get; set; }
        public Nullable<int> GROUP_SINGLE_MAX { get; set; }
        public Nullable<int> GROUP_BET_MAX { get; set; }
        public Nullable<int> GROUP_WIN_MAX { get; set; }
        public Nullable<int> GROUP_CASH_MAX { get; set; }
    }
}
