//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER_ACCOUNT
    {
        public int ACCOUNT_ID { get; set; }
        public string USER_ID { get; set; }
        public Nullable<int> ACCOUNT_MNY { get; set; }
        public Nullable<int> ACCOUNT_GAME_MNY { get; set; }
        public Nullable<int> ACCOUNT_STS { get; set; }
        public string ACCOUNT_CHKCOD { get; set; }
    }
}
