//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER_BASE
    {
        public T_USER_BASE()
        {
            USER_ID = "";
            USER_GROUP_ID = 0;
            USER_NAME = "";
            USER_PWD = "";
            USER_AGENT = "";
            USER_MOBIL = "";
            USER_BANK = "";
            USER_BANK_ACCOUNT = "";
            USER_ACC_PWD = "";
            USER_GROUP = 1;
            USER_AGENT_LEV = 1;
            USER_AGENT_STS = false;
            USER_AGENT_BOUNS = 1;
            USER_REG_TIME = DateTime.Now;
            USER_LAST_IP = "";
            USER_LAST_TIM = "";
            USER_CHK_COD = "";
        }
        public string USER_ID { get; set; }
        public Nullable<int> USER_GROUP_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PWD { get; set; }
        public string USER_AGENT { get; set; }
        public string USER_MOBIL { get; set; }
        public string USER_BANK { get; set; }
        public string USER_BANK_ACCOUNT { get; set; }
        public string USER_ACC_PWD { get; set; }
        public Nullable<int> USER_GROUP { get; set; }
        public Nullable<int> USER_AGENT_LEV { get; set; }
        public Nullable<bool> USER_AGENT_STS { get; set; }
        public Nullable<double> USER_AGENT_BOUNS { get; set; }
        public Nullable<int> USER_STS { get; set; }
        public Nullable<System.DateTime> USER_REG_TIME { get; set; }
        public string USER_LAST_IP { get; set; }
        public string USER_LAST_TIM { get; set; }
        public string USER_CHK_COD { get; set; }
    }
}
