//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GAME_ORDER
    {
        public int ORDER_ID { get; set; }
        public string ORDER_GRP { get; set; }
        public Nullable<int> ORDER_KIND { get; set; }
        public Nullable<int> ORDER_GAME_ID { get; set; }
        public Nullable<int> ORDER_BETKIND { get; set; }
        public Nullable<int> ORDER_BETTEAM { get; set; }
        public Nullable<int> ORDER_BETMONEY { get; set; }
        public Nullable<int> ORDER_BETID { get; set; }
        public Nullable<double> ORDER_BET { get; set; }
        public Nullable<System.DateTime> ORDER_TIME { get; set; }
        public string CHK_CODE { get; set; }
        public Nullable<int> ORDER_RET { get; set; }
        public string CHK_RETCOD { get; set; }
    }
}
