//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GAME_RET
    {
        public int RET_ID { get; set; }
        public Nullable<int> GAME_ID { get; set; }
        public Nullable<int> M_POINT { get; set; }
        public Nullable<int> C_POINT { get; set; }
        public Nullable<System.DateTime> RET_TIME { get; set; }
        public Nullable<int> RET_STS { get; set; }
        public string CHK_COD { get; set; }
    }
}
