//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GAME_TEAM
    {
        public int TEAM_ID { get; set; }
        public string TEAM_NAME { get; set; }
        public string TEAM_ENNAME { get; set; }
        public string TEAM_COUNTRY { get; set; }
        public string TEAM_LOGO { get; set; }
    }
}
