//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LEAGUE
    {
        public int LEAGUE_ID { get; set; }
        public string LEAGUE_NAME { get; set; }
        public Nullable<int> LEAGUE_KIND { get; set; }
        public string LEAGUE_LOGO { get; set; }
        public string LEAGUE_ENNAME { get; set; }
        public string LEAGUE_ORG { get; set; }
    }
}
