//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER_GROUP
    {
        public int USER_GROUP_ID { get; set; }
        public Nullable<int> USER_GROUP { get; set; }
        public Nullable<int> GROUP_ACC_MAX { get; set; }
        public Nullable<double> GROUP_RET_RETIO { get; set; }
        public Nullable<int> GROUP_SINGLE_MAX { get; set; }
        public Nullable<int> GROUP_BET_MAX { get; set; }
        public Nullable<int> GROUP_WIN_MAX { get; set; }
        public Nullable<int> GROUP_CASH_MAX { get; set; }
    }
}
