//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER_ACC_DTL
    {
        public int ACC_DTL_ID { get; set; }
        public string USER_ID { get; set; }
        public Nullable<int> ACC_DTL_MNY { get; set; }
        public Nullable<int> ACC_DTL_IO { get; set; }
        public Nullable<int> ACC_DTL_CUR { get; set; }
        public Nullable<System.DateTime> ACC_DTL_TIM { get; set; }
        public string ACC_DTL_IP { get; set; }
    }
}
