//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER_LOGIN
    {
        public int USER_LOGIN_ID { get; set; }
        public string USER_ID { get; set; }
        public Nullable<System.DateTime> USER_LOGIN_TIM { get; set; }
        public string USER_LOGIN_IP { get; set; }
        public string USER_LOGIN_REF { get; set; }
    }
}
