//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER_BASE
    {
        public string USER_ID { get; set; }
        public Nullable<int> USER_GROUP_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PWD { get; set; }
        public string USER_AGENT { get; set; }
        public string USER_MOBIL { get; set; }
        public string USER_BANK { get; set; }
        public string USER_BANK_ACCOUNT { get; set; }
        public string USER_ACC_PWD { get; set; }
        public Nullable<int> USER_GROUP { get; set; }
        public Nullable<int> USER_AGENT_LEV { get; set; }
        public Nullable<bool> USER_AGENT_STS { get; set; }
        public Nullable<double> USER_AGENT_BOUNS { get; set; }
        public Nullable<int> USER_STS { get; set; }
        public Nullable<System.DateTime> USER_REG_TIME { get; set; }
        public string USER_LAST_IP { get; set; }
        public string USER_LAST_TIM { get; set; }
        public string USER_CHK_COD { get; set; }
    }
}
