//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toto.Logic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TotoLocalDbEntities : DbContext
    {
        public TotoLocalDbEntities()
            : base("name=TotoLocalDbEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_ACCOUNT_CASH> T_ACCOUNT_CASH { get; set; }
        public DbSet<T_ALERT_MSG> T_ALERT_MSG { get; set; }
        public DbSet<T_GAME> T_GAME { get; set; }
        public DbSet<T_GAME_BET> T_GAME_BET { get; set; }
        public DbSet<T_GAME_ORDER> T_GAME_ORDER { get; set; }
        public DbSet<T_GAME_RET> T_GAME_RET { get; set; }
        public DbSet<T_GAME_TEAM> T_GAME_TEAM { get; set; }
        public DbSet<T_LEAGUE> T_LEAGUE { get; set; }
        public DbSet<T_MESSAGE_BOX> T_MESSAGE_BOX { get; set; }
        public DbSet<T_SITE> T_SITE { get; set; }
        public DbSet<T_USER_ACC_DTL> T_USER_ACC_DTL { get; set; }
        public DbSet<T_USER_ACCOUNT> T_USER_ACCOUNT { get; set; }
        public DbSet<T_USER_BASE> T_USER_BASE { get; set; }
        public DbSet<T_USER_GROUP> T_USER_GROUP { get; set; }
        public DbSet<T_USER_LOGIN> T_USER_LOGIN { get; set; }
        public DbSet<T_GAME_KIND> T_GAME_KIND { get; set; }
    }
}
